spring.application.name=literAlura
spring.datasource.url =jdbc:postgresql://HOST/BASEDEDATOS/CAMBIAR
spring.datasource.username =postgres
spring.datasource.password=CONTRASEÑA
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect